<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_1._0_FreeSqlQuickStart</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql.Provider.SqlServer" Version="3.2.815" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeSql.DBCore\FreeSql.DBCore.csproj" />
  </ItemGroup>

</Project>
